//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Ароматный_Мир.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Article { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MeasurementUnitID { get; set; }
        public int CategoryID { get; set; }
        public int ManufacturerID { get; set; }
        public int VendorID { get; set; }
        public decimal Cost { get; set; }
        public byte CurrentDiscount { get; set; }
        public byte MaximumDiscount { get; set; }
        public int QuantityInStock { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
